version: '3.9'
name: {{PROJECT_NAME}}-deployment
services:
  service:
    image: {{SERVICE_IMAGE}}
    healthcheck:
      test: ["CMD-SHELL", "curl -X GET -f http://service:9080/management/health/liveness || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 20s
    restart: always
    environment:
      HOST_IP: {{HOST_IP}}
      ROOT_FOLDER: /filecloud
    volumes:
      - {{LOCAL_FOLDER}}/files:/filecloud
    entrypoint: ["sh","init.sh"]
  app:
    image: {{APP_IMAGE}}
    depends_on:
      - service
    ports:
      - 3000:3000
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -X GET -f http://service:9080/management/health/liveness || exit 1"]
    #   interval: 15s
    #   timeout: 5s
    #   retries: 6
    #   start_period: 20s
    restart: always
    environment:
      SERVICE_HOST: service
      SERVICE_PORT: 8080