server:
  port: ${PORT:8080}
  servlet:
    context-path: /filecloud

management:
  server:
    port: 9080
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

storage:
  host: ${HOST_IP:null}
  trash:
    ttl: ${TRASH_TTL:30}
  local:
    folder: ${ROOT_FOLDER:"./filecloud"}

database:
  r2dbc:
    database: ${DB_DATABASE}
    schema: ${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    host: ${DB_HOST}
    port: ${DB_PORT}